TMPDIR = "${TOPDIR}/tmp-${DISTRO_CODENAME}-pv-mcu-zephyr-${MCU_ZEPHYR_MACHINE}"
DISTRO = "panta-zephyr"
MACHINE = "${MCU_ZEPHYR_MACHINE}"
ZEPHYR_BOARD = "${MCU_ZEPHYR_BOARD}"
DEPLOY_DIR_IMAGE = "${TMPDIR}/deploy/images/${MACHINE}"
