#!/bin/sh

source /usr/share/pantavisor/pvtest/utils


pvcontrol conf ls | jq '.[] | select(.key == "PV_LOG_PUSH")'

# let ph logger push some logs
sleep 20

device_id=`cat /var/run/pantavisor/pv/device-id`
output=`mktemp`
pvr device logs "$device_id" -r 0 > "$output" &

# let pvr get some logs
sleep 20

if [ -s "$output" ]; then
	echo "true"
else
	echo "false"
fi
