#!/usr/bin/env python3
"""Generate the release-containers workflow from containers.json.

One matrix entry per machine: each job builds every tag-listed container for
that machine in a single kas run, then uploads them one by one. Machines run
one after another (max-parallel: 1), which also keeps the jobs from
read-modify-writing containers-releases.json at once. The container
list itself is resolved at build time by .github/scripts/container-targets, so
adding a container to an existing machine needs no regeneration.
"""

import json

with open(".github/containers.json") as f:
    data = json.load(f)

branch = data["yocto_branch"]
containers = [c for c in data["containers"] if "tag" in c.get("workflows", [])]
outfile = ".github/workflows/release-containers.yaml"

machines = sorted({m for c in containers for m in c.get("machine", [])})

release_lines = [
    "# ##############################################################################",
    "# DO NOT EDIT — auto-generated by .github/scripts/make-containers-tag-matrix.py",
    "# Edit that script (and .github/containers.json), then run:",
    "#   .github/scripts/makeworkflows",
    "# Manual changes here will be overwritten on the next run.",
    "# ##############################################################################",
    "",
    'name: "ontag: build and upload containers"',
    "",
    "on:",
    "  workflow_call:",
    "",
    "jobs:",
    "  build:",
    '    name: "build (${{ matrix.machine }})"',
    "    strategy:",
    "      fail-fast: false",
    "      max-parallel: 1",
    "      matrix:",
    "        include:",
]

for machine in machines:
    release_lines += [
        f"          - machine: {machine}",
        f"            configs: kas/build-configs/release/containers/{machine}-{branch}.yaml:kas/build-configs/shared-vols.yaml",
    ]

release_lines += [
    "    uses: ./.github/workflows/buildkas-upload-container.yaml",
    "    with:",
    "      configs: ${{ matrix.configs }}",
    "      machine: ${{ matrix.machine }}",
    "      workflow: tag",
    "    secrets: inherit",
]

with open(outfile, "w") as f:
    f.write("\n".join(release_lines) + "\n")

print(f"new release-containers workflow: {outfile}")
