#!/usr/bin/env python3
"""Generate the onpush matrix workflow from machines.json."""

import json

with open(".github/machines.json") as f:
    data = json.load(f)

branch = data["yocto_branch"]
machines = [m for m in data["machines"] if "onpush" in m.get("workflows", [])]

# Machines with "pvtest" get a dedicated named job so pvtest steps can depend
# on them; all others go into the build-hw matrix.
hw_machines = [m for m in machines if not m.get("pvtest")]
pvtest_machines = [m for m in machines if m.get("pvtest")]

outfile = f".github/workflows/onpush-{branch}.yaml"

lines = [
    "# ##############################################################################",
    "# DO NOT EDIT — auto-generated by .github/scripts/make-onpush-matrix.py",
    "# Edit that script (and .github/machines.json), then run:",
    "#   .github/scripts/makeworkflows",
    "# Manual changes here will be overwritten on the next run.",
    "# ##############################################################################",
    "",
    f'name: "onpush: {branch}"',
    "",
    "on:",
    "  push:",
    "    paths:",
    "      - '**'",
    "      # Skip pushes that only touch CI internals (generators,",
    "      # docs templates, badge upload helper, …) — these don't",
    "      # change what's built.",
    "      - '!.github/**'",
    "      # …but the reusable build workflow and this matrix file",
    "      # itself ARE part of what's built; re-include them so",
    "      # changes to the build pipeline retrigger CI.",
    "      - '.github/workflows/buildkas-target.yaml'",
]

if pvtest_machines:
    lines.append("      - '.github/workflows/call-pvtests.yaml'")

lines += [
    f"      - '.github/workflows/onpush-{branch}.yaml'",
    "  pull_request:",
    "    types: [ready_for_review]",
    "",
    "concurrency:",
    "  group: ${{ github.workflow }}-${{ github.ref }}",
    "  cancel-in-progress: true",
    "",
    "jobs:",
    "  check-draft:",
    "    runs-on: ubuntu-latest",
    "    outputs:",
    "      is_draft: ${{ steps.check.outputs.is_draft }}",
    "    steps:",
    "      - id: check",
    "        env:",
    "          GH_TOKEN: ${{ github.token }}",
    "        run: |",
    "          draft=$(gh pr list --repo ${{ github.repository }} --head ${{ github.ref_name }} --json isDraft --jq '.[0].isDraft // false')",
    '          echo "is_draft=$draft" >> $GITHUB_OUTPUT',
    "",
    "  build-hw:",
    "    needs: check-draft",
    "    if: needs.check-draft.outputs.is_draft != 'true'",
    '    name: "build (${{ matrix.machine_name }})"',
    "    strategy:",
    "      fail-fast: false",
    "      matrix:",
    "        include:",
]

for m in hw_machines:
    name = m["name"]
    build_target = m.get("build_target", "pantavisor-starter")
    output = m.get("output", "pantavisor-starter*.rootfs.wic*").strip()
    sdk = 1 if m.get("sdk") == 1 else 0
    lines += [
        f"          - machine_name: {name}-{branch}",
        f"            configs: kas/build-configs/release/{name}-{branch}.yaml:kas/build-configs/shared-vols.yaml",
        f"            build_target: {build_target}",
        f'            output: "{output}"',
        f"            sdk: {sdk}",
    ]

lines += [
    "    uses: ./.github/workflows/buildkas-target.yaml",
    "    with:",
    "      configs: ${{ matrix.configs }}",
    "      machine_name: ${{ matrix.machine_name }}",
    "      build_target: ${{ matrix.build_target }}",
    "      output: ${{ matrix.output }}",
    "      sdk: ${{ matrix.sdk }}",
    "    secrets: inherit",
]

# Dedicated named build job + pvtest jobs for each pvtest machine.
# Job ID is "build-<first-segment-of-machine-name>" (e.g. docker-x86_64 → build-docker).
pvtest_build_job_ids = []
for m in pvtest_machines:
    name = m["name"]
    build_target = m.get("build_target", "pantavisor-starter")
    output = m.get("output", "pantavisor-starter*.rootfs.wic*").strip()
    sdk = 1 if m.get("sdk") == 1 else 0
    job_id = "build-" + name.split("-")[0]
    pvtest_build_job_ids.append(job_id)

    lines += [
        "",
        f"  {job_id}:",
        "    needs: check-draft",
        "    if: needs.check-draft.outputs.is_draft != 'true'",
        f'    name: "build ({name}-{branch})"',
        "    uses: ./.github/workflows/buildkas-target.yaml",
        "    with:",
        f"      configs: kas/build-configs/release/{name}-{branch}.yaml:kas/build-configs/shared-vols.yaml",
        f"      machine_name: {name}-{branch}",
        f"      build_target: {build_target}",
        f'      output: "{output}"',
        f"      sdk: {sdk}",
        "    secrets: inherit",
    ]

    for test_path in m.get("pvtest", []):
        test_name = test_path.split("/")[-1]
        lines += [
            "",
            f"  pvtest-{test_name}:",
            f"    needs: {job_id}",
            "    uses: ./.github/workflows/call-pvtests.yaml",
            "    with:",
            f"      test_path: {test_path}",
            "    secrets: inherit",
        ]

all_build_job_ids = ["build-hw"] + pvtest_build_job_ids
summary_needs = ["check-draft"] + all_build_job_ids
needs_str = f"[{', '.join(summary_needs)}]"

lines += [
    "",
    "  summary:",
    f"    needs: {needs_str}",
    "    if: always()",
    "    runs-on: ubuntu-latest",
    "    steps:",
    "      - name: Build Summary",
    "        env:",
    "          GH_TOKEN: ${{ github.token }}",
    "        run: |",
    '          echo "## Build Summary" >> $GITHUB_STEP_SUMMARY',
    '          echo "" >> $GITHUB_STEP_SUMMARY',
    '          echo "| Machine | Result |" >> $GITHUB_STEP_SUMMARY',
    '          echo "| :--- | :--- |" >> $GITHUB_STEP_SUMMARY',
    """          gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs | jq -r '.jobs[] | select(.name | startswith("build (")) | "| " + (.name | ltrimstr("build (") | rtrimstr(")")) + " | " + (if .conclusion == "success" then "✅" elif .conclusion == "failure" then "❌" elif .conclusion == "cancelled" then "🚫" elif .conclusion == "skipped" then "⏭️" else (.conclusion // "🔄") end) + " |"' >> $GITHUB_STEP_SUMMARY""",
]

with open(outfile, "w") as f:
    f.write("\n".join(lines) + "\n")

print(f"new onpush matrix workflow: {outfile}")
