#!/usr/bin/env python3
"""Generate the container build workflows from containers.json.

buildkas-containers.yaml is the reusable build: given a machine and a list of
containers (or "all"), it builds every listed container that supports that
machine in one kas run, then publishes each pvrexport as its own artifact.
Both the manual dispatch and onpush-containers.yaml call it.

The manual dispatch takes a machine and a container, where container
defaults to "all": every manual-listed container supporting that machine.
workflow_dispatch choice inputs can't be filtered dynamically based on
another input's value, so "machine" lists the union of every machine in any
manual-listed container; with a single container picked, the resolve step
rejects a (container, machine) pair that container doesn't list (e.g.
pv-debian-nm is docker-x86_64 only).
"""

import json

with open(".github/containers.json") as f:
    data = json.load(f)

branch = data["yocto_branch"]
manual = [c for c in data["containers"] if "manual" in c.get("workflows", [])]

HEADER = """\
# ##############################################################################
# DO NOT EDIT — auto-generated by .github/scripts/make-containers-dispatch.py
# Edit that script (and .github/containers.json), then run:
#   .github/scripts/makeworkflows
# Manual changes here will be overwritten on the next run.
# ##############################################################################
"""

container_options = "\n".join(f"          - {name}" for name in ["all"] + [c["name"] for c in manual])
all_machines = sorted({m for c in manual for m in c.get("machine", [])})
machine_options = "\n".join(f"          - {name}" for name in all_machines)

# upload-artifact can't loop, so emit one step per container; containers
# that weren't built for this run have no file and are skipped by
# if-no-files-found: ignore.
split_steps = "".join(
    f"""
      - uses: actions/upload-artifact@v7
        with:
          name: {c["name"]}-${{{{ inputs.machine }}}}-{branch}
          path: build/{c["output"]}
          compression-level: 0
          if-no-files-found: ignore"""
    for c in data["containers"]
)

build_containers = f"""\
{HEADER}
name: "build containers"

on:
  workflow_call:
    inputs:
      machine:
        required: true
        type: string
      containers:
        description: 'Space-separated container names, or "all" for every manual-listed one; those not supporting the machine are skipped'
        required: false
        type: string
        default: all

jobs:
  resolve:
    runs-on: ubuntu-latest
    outputs:
      build_target: ${{{{ steps.lookup.outputs.build_target }}}}
      output: ${{{{ steps.lookup.outputs.output }}}}
    steps:
      - uses: actions/checkout@v6
      - id: lookup
        env:
          CONTAINERS: ${{{{ inputs.containers }}}}
          MACHINE: ${{{{ inputs.machine }}}}
        run: |
          if [ "$CONTAINERS" = all ]; then
            args=(--workflow manual)
          else
            args=(--container "$CONTAINERS")
          fi
          build_target=$(.github/scripts/container-targets "${{args[@]}}" --list build_target "$MACHINE" | xargs)
          output=$(.github/scripts/container-targets "${{args[@]}}" --list output "$MACHINE" | xargs)
          if [ -z "$build_target" ]; then
            echo "::error::none of '$CONTAINERS' supports machine $MACHINE"
            exit 1
          fi
          echo "building for $MACHINE: $build_target"
          echo "build_target=$build_target" >> $GITHUB_OUTPUT
          echo "output=$output" >> $GITHUB_OUTPUT

  build:
    needs: resolve
    uses: ./.github/workflows/buildkas-target.yaml
    with:
      configs: kas/build-configs/release/containers/${{{{ inputs.machine }}}}-{branch}.yaml:kas/build-configs/shared-vols.yaml
      machine_name: containers-${{{{ inputs.machine }}}}-{branch}
      build_target: ${{{{ needs.resolve.outputs.build_target }}}}
      output: ${{{{ needs.resolve.outputs.output }}}}
      keep_going: true
    secrets: inherit

  # buildkas-target hands back one combined artifact from the self-hosted
  # runner; re-publish it as one artifact per container, then drop the
  # combined one. Runs after a partial -k build too, so whatever built ships.
  split:
    needs: [resolve, build]
    if: always() && needs.resolve.result == 'success'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    env:
      COMBINED: build-containers-${{{{ inputs.machine }}}}-{branch}
    steps:
      - uses: actions/download-artifact@v7
        with:
          name: ${{{{ env.COMBINED }}}}
          path: build
{split_steps}

      - name: delete combined artifact
        env:
          GH_TOKEN: ${{{{ github.token }}}}
        run: |
          id=$(gh api "repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/artifacts" \\
                 --jq ".artifacts[] | select(.name == \\"$COMBINED\\") | .id")
          [ -z "$id" ] || gh api -X DELETE "repos/$GITHUB_REPOSITORY/actions/artifacts/$id"
"""

manual_dispatch = f"""\
{HEADER}
name: "manual containers: {branch}"

on:
  workflow_dispatch:
    inputs:
      machine:
        description: 'Target architecture'
        required: true
        type: choice
        options:
{machine_options}
      container:
        description: 'Container to build ("all" = every container supporting the machine, in one kas run)'
        required: true
        default: all
        type: choice
        options:
{container_options}

jobs:
  build:
    permissions:
      contents: read
      actions: write
    uses: ./.github/workflows/buildkas-containers.yaml
    with:
      machine: ${{{{ inputs.machine }}}}
      containers: ${{{{ inputs.container }}}}
    secrets: inherit
"""

for outfile, content in [
    (".github/workflows/buildkas-containers.yaml", build_containers),
    (f".github/workflows/manual-containers-{branch}.yaml", manual_dispatch),
]:
    with open(outfile, "w") as f:
        f.write(content)
    print(f"new containers workflow: {outfile}")
