#!/usr/bin/env python3
"""Generate the onpush matrix workflow from machines.json."""

import json

with open(".github/machines.json") as f:
    data = json.load(f)

branch = data["yocto_branch"]
machines = [m for m in data["machines"] if "onpush" in m.get("workflows", [])]

# Machines with "pvtest" get a dedicated named job so pvtest steps can depend
# on them; all others go into the build-hw matrix.
hw_machines = [m for m in machines if not m.get("pvtest")]
pvtest_machines = [m for m in machines if m.get("pvtest")]

outfile = f".github/workflows/onpush-{branch}.yaml"

# Picks the pvtest legs from the changed files; mirrors pantavisor's onpush-pvtest.yaml.
SCOPE_SCRIPT = r"""set -euo pipefail

# lv/lp = local volatile/persistent, rv/rp = remote volatile/persistent
lv= lp= rv= rp=

pr='${{ github.event.pull_request.number }}'
if [ -n "$pr" ]; then
  files=$(gh api --paginate \
    "repos/${{ github.repository }}/pulls/$pr/files" --jq '.[].filename')
else
  base='${{ github.event.before }}'
  case "$base" in
    ''|0000000000000000000000000000000000000000)
      # new branch, or a force-push whose base is gone: no diff to
      # trust, so run everything rather than silently skip any of it
      files=everything ;;
    *)
      files=$(gh api "repos/${{ github.repository }}/compare/$base...${{ github.sha }}" \
        --jq '.files[].filename')
      if [ "$(printf '%s\n' "$files" | grep -c .)" -ge 300 ]; then
        files=everything
      fi ;;
  esac
fi

if [ "$files" = everything ]; then
  lv=1 lp=1 rv=1 rp=1
else
  while IFS= read -r f; do
    case "$f" in
      ''|docs/*|CHANGELOG/*) ;;
      # the pantavisor pin, the pvtest fixtures, pvr and the pvtest assembly
      recipes-pv/pantavisor/pantavisor.inc|recipes-containers/pv-examples/*|recipes-pv/pvr/*) lv=1 lp=1 rv=1 rp=1 ;;
      recipes-pv/pantavisor/pantavisor-appengine-distro.bb|*/pantavisor-appengine-tester.bb) lv=1 lp=1 rv=1 rp=1 ;;
      *) lv=1 ;;
    esac
  done <<< "$files"
fi

# only the scopes this machine is listed for in machines.json
case " @ALLOWED@ " in *" local "*) ;; *) lv= lp= ;; esac
case " @ALLOWED@ " in *" remote "*) ;; *) rv= rp= ;; esac

# never hand the pvtest job an empty matrix
if [ -z "$lv$lp$rv$rp" ]; then
  lv=1
fi

matrix=$(printf '%s\n' ${lv:+local/volatile} ${lp:+local/persistent} \
  ${rv:+remote/volatile} ${rp:+remote/persistent} \
  | jq -Rnc '[inputs | split("/") | {scope: .[0], model: .[1]}]')

echo "matrix=$matrix" >> "$GITHUB_OUTPUT"
echo "### pvtest matrix: \`$matrix\`" >> "$GITHUB_STEP_SUMMARY"
"""

lines = [
    "# ##############################################################################",
    "# DO NOT EDIT — auto-generated by .github/scripts/make-onpush-matrix.py",
    "# Edit that script (and .github/machines.json), then run:",
    "#   .github/scripts/makeworkflows",
    "# Manual changes here will be overwritten on the next run.",
    "# ##############################################################################",
    "#",
    "# pvtest jobs are picked per changed file, and the run is their union:",
    "#   recipes-pv/pantavisor/pantavisor.inc (pin),",
    "#   recipes-containers/pv-examples/, recipes-pv/pvr/,",
    "#   pantavisor-appengine-{distro,tester}.bb   local + remote (volatile + persistent)",
    "#   anything else but docs/ and CHANGELOG/     local  (volatile)",
    "# See docs/overview/ci/builds.md \"CI coverage\".",
    "",
    f'name: "onpush: {branch}"',
    "",
    "on:",
    "  push:",
    "    branches:",
    "      - '**'",
    "    paths-ignore:",
    "      # Deliberately covers .github/** as a whole: a change to the build",
    "      # workflows or this matrix does not re-trigger onpush on its own.",
    "      - '.github/**'",
    "      - 'CHANGELOG/**'",
    "      - 'docs/**'",
    "  pull_request:",
    "    types: [opened, synchronize, ready_for_review]",
    "",
    "concurrency:",
    "  group: ${{ github.workflow }}-${{ github.event.pull_request.head.ref || github.ref_name }}",
    "  cancel-in-progress: ${{ (github.event.pull_request.head.ref || github.ref_name) != 'master' }}",
    "",
    "jobs:",
    "  check-draft:",
    "    runs-on: ubuntu-latest",
    "    outputs:",
    "      is_draft: ${{ steps.check.outputs.is_draft }}",
    "    steps:",
    "      - id: check",
    "        env:",
    "          GH_TOKEN: ${{ github.token }}",
    "        run: |",
    "          draft='${{ github.event.pull_request.draft }}'",
    "          # push events carry no PR: look it up by branch",
    "          [ -n \"$draft\" ] || draft=$(gh pr list --repo ${{ github.repository }} --head ${{ github.ref_name }} --json isDraft --jq '.[0].isDraft // false')",
    '          echo "is_draft=$draft" >> $GITHUB_OUTPUT',
    "",
    "  build-hw:",
    "    needs: check-draft",
    "    if: needs.check-draft.outputs.is_draft != 'true'",
    '    name: "build (${{ matrix.machine_name }})"',
    "    strategy:",
    "      fail-fast: false",
    "      matrix:",
    "        include:",
]

for m in hw_machines:
    name = m["name"]
    build_target = m.get("build_target", "pantavisor-starter")
    output = m.get("output", "pantavisor-starter*.rootfs.wic*").strip()
    sdk = 1 if m.get("sdk") == 1 else 0
    lines += [
        f"          - machine_name: {name}-{branch}",
        f"            configs: kas/build-configs/release/{name}-{branch}.yaml:kas/build-configs/shared-vols.yaml",
        f"            build_target: {build_target}",
        f'            output: "{output}"',
        f"            sdk: {sdk}",
    ]

lines += [
    "    uses: ./.github/workflows/buildkas-target.yaml",
    "    with:",
    "      configs: ${{ matrix.configs }}",
    "      machine_name: ${{ matrix.machine_name }}",
    "      build_target: ${{ matrix.build_target }}",
    "      output: ${{ matrix.output }}",
    "      sdk: ${{ matrix.sdk }}",
    "    secrets: inherit",
]

# Dedicated named build job + pvtest jobs for each pvtest machine.
# Job ID is "build-<first-segment-of-machine-name>" (e.g. docker-x86_64 → build-docker).
pvtest_build_job_ids = []
scope_job_ids = []
for m in pvtest_machines:
    name = m["name"]
    build_target = m.get("build_target", "pantavisor-starter")
    output = m.get("output", "pantavisor-starter*.rootfs.wic*").strip()
    sdk = 1 if m.get("sdk") == 1 else 0
    job_id = "build-" + name.split("-")[0]
    pvtest_build_job_ids.append(job_id)

    lines += [
        "",
        f"  {job_id}:",
        "    needs: check-draft",
        "    if: needs.check-draft.outputs.is_draft != 'true'",
        f'    name: "build ({name}-{branch})"',
        "    uses: ./.github/workflows/buildkas-target.yaml",
        "    with:",
        f"      configs: kas/build-configs/release/{name}-{branch}.yaml:kas/build-configs/shared-vols.yaml",
        f"      machine_name: {name}-{branch}",
        f"      build_target: {build_target}",
        f'      output: "{output}"',
        f"      sdk: {sdk}",
        "    secrets: inherit",
    ]

    short = name.split("-")[0]
    scope_job_ids.append(f"scope-{short}")
    allowed = " ".join(m["pvtest"])
    lines += [
        "",
        f"  scope-{short}:",
        "    needs: check-draft",
        "    if: needs.check-draft.outputs.is_draft != 'true'",
        "    runs-on: ubuntu-latest",
        "    outputs:",
        "      matrix: ${{ steps.pick.outputs.matrix }}",
        "    steps:",
        "      - id: pick",
        "        env:",
        "          GH_TOKEN: ${{ github.token }}",
        "        run: |",
    ] + ["          " + l if l else "" for l in SCOPE_SCRIPT.replace("@ALLOWED@", allowed).splitlines()] + [
        "",
        f"  pvtest-{short}:",
        f"    needs: [{job_id}, scope-{short}]",
        '    name: "pvtest (${{ matrix.scope }}, ${{ matrix.model }})"',
        "    strategy:",
        "      fail-fast: false",
        "      matrix:",
        f"        include: ${{{{ fromJSON(needs.scope-{short}.outputs.matrix) }}}}",
        "    uses: ./.github/workflows/call-pvtests.yaml",
        "    with:",
        "      test_path: ${{ matrix.scope }}",
        '      parallel: "6"',
        "      model: ${{ matrix.model }}",
        "    secrets: inherit",
    ]

all_build_job_ids = ["build-hw"] + pvtest_build_job_ids
summary_needs = ["check-draft"] + all_build_job_ids
needs_str = f"[{', '.join(summary_needs)}]"

lines += [
    "",
    "  summary:",
    f"    needs: {needs_str}",
    "    if: always()",
    "    runs-on: ubuntu-latest",
    "    steps:",
    "      - name: Build Summary",
    "        env:",
    "          GH_TOKEN: ${{ github.token }}",
    "        run: |",
    '          echo "## Build Summary" >> $GITHUB_STEP_SUMMARY',
    '          echo "" >> $GITHUB_STEP_SUMMARY',
    '          echo "| Machine | Result |" >> $GITHUB_STEP_SUMMARY',
    '          echo "| :--- | :--- |" >> $GITHUB_STEP_SUMMARY',
    """          gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs | jq -r '.jobs[] | select(.name | startswith("build (")) | "| " + (.name | ltrimstr("build (") | rtrimstr(")")) + " | " + (if .conclusion == "success" then "✅" elif .conclusion == "failure" then "❌" elif .conclusion == "cancelled" then "🚫" elif .conclusion == "skipped" then "⏭️" else (.conclusion // "🔄") end) + " |"' >> $GITHUB_STEP_SUMMARY""",
]

with open(outfile, "w") as f:
    f.write("\n".join(lines) + "\n")

print(f"new onpush matrix workflow: {outfile}")
