#!/usr/bin/env python3
"""Generate the manual containers-dispatch workflow from containers.json.

Unlike the old fan-out-over-every-listed-machine behavior, this dispatch
takes two inputs — container and machine — and builds exactly that one
combination. workflow_dispatch choice inputs can't be filtered dynamically
based on another input's value, so "machine" lists the union of every
machine that appears in any manual-listed container's "machine" array; the
resolve step then rejects a (container, machine) pair that isn't actually
in that container's list, since not every container supports every machine
(e.g. pv-debian-nm is docker-x86_64 only).
"""

import json

with open(".github/containers.json") as f:
    data = json.load(f)

branch = data["yocto_branch"]
containers = [c for c in data["containers"] if "manual" in c.get("workflows", [])]
outfile = f".github/workflows/manual-containers-{branch}.yaml"

container_names = [c["name"] for c in containers]
container_options = "\n".join(f"          - {name}" for name in container_names)

all_machines = sorted({m for c in containers for m in c.get("machine", [])})
machine_options = "\n".join(f"          - {name}" for name in all_machines)

content = f"""\
# ##############################################################################
# DO NOT EDIT — auto-generated by .github/scripts/make-containers-dispatch.py
# Edit that script (and .github/containers.json), then run:
#   .github/scripts/makeworkflows
# Manual changes here will be overwritten on the next run.
# ##############################################################################

name: "manual containers: {branch}"

on:
  workflow_dispatch:
    inputs:
      container:
        description: 'Container to build'
        required: true
        type: choice
        options:
{container_options}
      machine:
        description: 'Target architecture'
        required: true
        type: choice
        options:
{machine_options}

jobs:
  resolve:
    runs-on: ubuntu-latest
    outputs:
      build_target: ${{{{ steps.lookup.outputs.build_target }}}}
      output: ${{{{ steps.lookup.outputs.output }}}}
    steps:
      - uses: actions/checkout@v6
      - id: lookup
        run: |
          container="${{{{ inputs.container }}}}"
          machine="${{{{ inputs.machine }}}}"
          machines=$(jq -c --arg c "$container" '.containers[] | select(.name == $c) | .machine' .github/containers.json)
          if ! jq -e --arg m "$machine" 'index($m) != null' <<< "$machines" > /dev/null; then
            echo "::error::$container does not support machine $machine (supported: $(jq -c . <<< "$machines"))"
            exit 1
          fi
          build_target=$(jq -r --arg c "$container" '.containers[] | select(.name == $c) | .build_target' .github/containers.json)
          output=$(jq -r --arg c "$container" '.containers[] | select(.name == $c) | .output' .github/containers.json)
          echo "build_target=$build_target" >> $GITHUB_OUTPUT
          echo "output=$output" >> $GITHUB_OUTPUT

  build:
    needs: resolve
    uses: ./.github/workflows/buildkas-target.yaml
    with:
      configs: kas/build-configs/release/containers/${{{{ inputs.machine }}}}-{branch}.yaml:kas/build-configs/shared-vols.yaml
      machine_name: ${{{{ inputs.container }}}}-${{{{ inputs.machine }}}}-{branch}
      build_target: ${{{{ needs.resolve.outputs.build_target }}}}
      output: ${{{{ needs.resolve.outputs.output }}}}
    secrets: inherit
"""

with open(outfile, "w") as f:
    f.write(content)

print(f"new manual containers-dispatch workflow: {outfile}")
