#!/bin/bash

set -e

yocto_branch=$(jq -r .yocto_branch .github/machines.json)

configs=$(jq -r '.machines[] | .config' .github/machines.json)
names=$(jq -r '.machines[] | .name' .github/machines.json)

echo "Processing machines for branch: $yocto_branch"
echo ""

rm -f .github/configs/release/*-$yocto_branch.yaml*

readarray -t config_array <<< "$configs"
readarray -t name_array <<< "$names"

for i in "${!config_array[@]}"; do
    cc="${config_array[$i]}"
    m="${name_array[$i]}"
    
    echo "Processing: $m"
    echo "Config: $cc"
    
    KAS_WORK_DIR=. kas dump --update --resolve-refs "kas/sourcedir.yaml:$cc" > .github/configs/release/$m-$yocto_branch.yaml
    
    echo "- Created config for machine: $m"
    echo ""
done

echo "All machine configs generated successfully!"

echo DIFF:
git diff HEAD .github/
