#!/bin/sh

# we call the delegate
delegate=$1
shift
. $delegate $@

bitbake-layers add-layer ../meta-pantavisor

sed -i '/### BEGIN META PANTAVISOR/,/### END META PANTAVISOR/d' $BUILDDIR/conf/local.conf

cat >> $BUILDDIR/conf/local.conf <<EOF

### BEGIN META PANTAVISOR

GOVERSION = "1.20%"

### END META PANTAVISOR
EOF
