#!/bin/sh

source=$BASH_SOURCE
dir=`dirname $source`
absdir=`sh -c "cd $dir; pwd"`

# we call the delegate
delegate=$1
shift
. $delegate $@

BB_ENV_PASSTHROUGH_ADDITIONS="${BB_ENV_PASSTHROUGH_ADDITIONS} PVROOT_IMAGE_BSP "
export BB_ENV_PASSTHROUGH_ADDITIONS 

# adding pantavisor meta
echo "Ensuring that Pantavisor meta is enabled ..."
bitbake-layers add-layer $absdir

echo "Setting required tweaks in conf/local.conf ..."

sed -i '/### BEGIN META PANTAVISOR/,/### END META PANTAVISOR/d' $BUILDDIR/conf/local.conf

cat >> $BUILDDIR/conf/local.conf <<EOF

### BEGIN META PANTAVISOR

GOVERSION = "1.20%"

### END META PANTAVISOR
EOF
