#!/bin/sh

src=$BASH_SOURCE
dir=`dirname $src`
absdir=`sh -c "cd $dir; pwd"`

# we call the delegate
delegate=$1
shift
. $delegate $@

# adding pantavisor meta
echo "Ensuring that Pantavisor meta is enabled ..."
bitbake-layers add-layer $absdir

echo "Setting required tweaks in conf/local.conf ..."

sed -i '/### BEGIN META PANTAVISOR/,/### END META PANTAVISOR/d' $BUILDDIR/conf/local.conf

cat >> $BUILDDIR/conf/local.conf <<EOF

### BEGIN META PANTAVISOR

KERNEL_CLASSES += "pvbsp"

# comment out if you want to rather manually add this
# to the image you want to extract a bsp pvrexport from
IMAGE_CLASSES += "bspimage-pvrexport"

GOVERSION = "1.20%"

PANTAVISOR_SYSTEM_DISTRO = "yes"

### END META PANTAVISOR
EOF
