#!/bin/sh

src=$BASH_SOURCE
dir=`dirname $src`
absdir=`sh -c "cd $dir; pwd"`

# we call the delegate
delegate=$1
shift
. $delegate $@

BB_ENV_PASSTHROUGH_ADDITIONS="${BB_ENV_PASSTHROUGH_ADDITIONS} PVROOT_IMAGE_BSP "
export BB_ENV_PASSTHROUGH_ADDITIONS 

# adding pantavisor meta
echo "Ensuring that Pantavisor meta is enabled ..."
bitbake-layers add-layer $absdir || true

echo "Setting required tweaks in conf/local.conf ..."

sed -i '/### BEGIN META PANTAVISOR/,/### END META PANTAVISOR/d' $BUILDDIR/conf/local.conf

cat >> $BUILDDIR/conf/local.conf <<EOF

### BEGIN META PANTAVISOR

# enable pvbsp kernel class to set correct initramfs
KERNEL_CLASSES += "pvbsp"

# enable bspimage-pvrexport class; This one will produce
# a bsp pvrexport from any image you build
IMAGE_CLASSES += "bspimage-pvrexport"

# enable image-pvrexport class; This one will produce
# a root container pvrexport from the rootfs of the images
# you build;  disable that if you just want the bsp.
IMAGE_CLASSES += "image-pvrexport"

# lets use our goversion
GOVERSION = "1.20%"

# enable system_distro build to bring in Xrecipes-core recipes
PANTAVISOR_SYSTEM_DISTRO = "yes"

# select mbedtls
PREFERRED_VERSION_mbedtls = "2.28.%"

DISTRO_FEATURES:remove = "usrmerge"
AGL_DEFAULT_DISTRO_FEATURES:remove = "usrmerge"

### END META PANTAVISOR
EOF
