SUMMARY = "pv-llama — on-device LLM inference container with multi-model swap"
DESCRIPTION = "Single OpenAI-compatible endpoint that exposes every local \
GGUF this image bundles. llama-swap manages llama-server lifecycle: each \
request's `model` field selects a backend (`local-qwen`, `local-deepseek-r1`, \
…) and llama-swap spawns/swaps the matching llama-server process under a \
configurable RAM budget. Cloud-provider routing (Anthropic / Bedrock / \
OpenAI) lives in a separate pv-llama-router container in front of this one."
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://${COMMON_LICENSE_DIR}/MIT;md5=0835ade698e0bcf8506ecda2f7b4f302"

inherit core-image container-pvrexport

# llama-swap ships only as aarch64 / x86_64 prebuilt binaries; running
# meaningful LLM inference on 32-bit ARM is impractical anyway. Skip
# the recipe cleanly on incompatible hosts so multiconfig builds that
# include other arches don't error out trying to resolve llama-swap.
COMPATIBLE_HOST = "(aarch64|x86_64).*-linux"

IMAGE_BASENAME = "${PN}"
PVRIMAGE_AUTO_MDEV = "0"

# Container userspace.
IMAGE_INSTALL += "llama-cpp llama-swap socat busybox"

do_fetch[noexec] = "0"
do_unpack[noexec] = "0"

# Models bundled into this image. Adding a new model = add a
# `pv-llama-model-<name>` recipe and append <name> here. Each model
# becomes its own data squashfs in the pvrexport (own pvr object), is
# mounted at /usr/share/pv-llama/models/<name>/, and gets registered
# with llama-swap as `local-<name>` in /v1/models.
LLAMA_MODELS ??= "deepseek-r1 qwen"

# Per-model defaults the generated llama-swap config will use. Override
# in a per-model fragment if a model needs more ctx / threads / ttl.
LLAMA_DEFAULT_CTX ??= "4096"
LLAMA_DEFAULT_THREADS ??= "4"
LLAMA_DEFAULT_TTL_SECONDS ??= "300"
# llama-swap waits this long for a freshly spawned llama-server's
# /health to return ready. 60s is too short for ≥1 GB GGUFs on slow
# storage — Pi 5 squashfs-mmap of a 1.1 GB Q4 model + graph init has
# been seen at 60–120 s. 300 s gives comfortable headroom for any
# bundled model.
LLAMA_HEALTH_CHECK_TIMEOUT ??= "300"

LLAMA_MODELS_DIR = "usr/share/pv-llama/models"

# Pull each model recipe in as a build-time dep so its squashfs lands
# in our sysroot and we can copy it into the staged container dir.
python __anonymous() {
    models = (d.getVar("LLAMA_MODELS") or "").split()
    deps = " ".join("pv-llama-model-%s" % m for m in models)
    d.appendVar("DEPENDS", " " + deps)
}

# Use += so we don't clobber SRC_URI entries inherited from pvr-ca
# (the pv-developer-ca tarball needed by `pvr sig add` at pvrexport time).
SRC_URI += "file://pv-llama-run.sh \
            file://pv-llama.services.json"

# Render args.json (PV_VOLUME_MOUNTS list) and the llama-swap config
# from the LLAMA_MODELS list so the recipe stays declarative.
python do_unpack:append() {
    import os
    workdir = d.getVar("WORKDIR")
    models = (d.getVar("LLAMA_MODELS") or "").split()
    mdir = d.getVar("LLAMA_MODELS_DIR")
    ctx = d.getVar("LLAMA_DEFAULT_CTX")
    threads = d.getVar("LLAMA_DEFAULT_THREADS")
    ttl = d.getVar("LLAMA_DEFAULT_TTL_SECONDS")
    health_timeout = d.getVar("LLAMA_HEALTH_CHECK_TIMEOUT")

    mounts = ",".join("%s.squashfs:%s/%s" % (m, mdir, m) for m in models)
    args_json = '{\n    "PV_VOLUME_MOUNTS": "%s"\n}\n' % mounts
    with open(os.path.join(workdir, "args.json"), "w") as f:
        f.write(args_json)

    yaml = []
    yaml.append("# Auto-generated by pv-llama_1.0.bb. Do not edit on the device;")
    yaml.append("# changes are overwritten by the next image update.")
    yaml.append("healthCheckTimeout: %s" % health_timeout)
    yaml.append("logLevel: info")
    yaml.append("models:")
    for m in models:
        gguf = "/%s/%s/model.gguf" % (mdir, m)
        yaml.append('  "local-%s":' % m)
        yaml.append('    cmd: |')
        yaml.append('      /usr/bin/llama-server')
        yaml.append('        --model %s' % gguf)
        yaml.append('        --port ${PORT}')
        yaml.append('        --host 127.0.0.1')
        yaml.append('        --ctx-size %s' % ctx)
        yaml.append('        --threads %s' % threads)
        yaml.append('    proxy: "http://127.0.0.1:${PORT}"')
        yaml.append('    ttl: %s' % ttl)
    yaml.append("")
    with open(os.path.join(workdir, "llama-swap.yaml"), "w") as f:
        f.write("\n".join(yaml))
}

install_pv_llama() {
    install -d ${IMAGE_ROOTFS}${bindir}
    install -m 0755 ${WORKDIR}/pv-llama-run.sh ${IMAGE_ROOTFS}${bindir}/pv-llama-run

    install -d ${IMAGE_ROOTFS}${sysconfdir}/pv-llama
    install -m 0644 ${WORKDIR}/llama-swap.yaml \
        ${IMAGE_ROOTFS}${sysconfdir}/pv-llama/llama-swap.yaml

    # Empty mountpoints — pantavisor bind-mounts each model squashfs
    # here at runtime according to PV_VOLUME_MOUNTS (args.json).
    for m in ${LLAMA_MODELS}; do
        install -d ${IMAGE_ROOTFS}/${LLAMA_MODELS_DIR}/$m
    done

    # services.json gets copied by container-pvrexport from WORKDIR.
    cp -f ${WORKDIR}/pv-llama.services.json ${WORKDIR}/services.json
}

ROOTFS_POSTPROCESS_COMMAND += "install_pv_llama; "

# Stage each model's squashfs (built by pv-llama-model-<name> and
# installed under ${datadir}/pv-llama/models/ in our sysroot) into the
# pvrexport tree so `pvr add`/`pvr commit` picks them up as their own
# objects.
build_model_squashfs() {
    for m in ${LLAMA_MODELS}; do
        src=${RECIPE_SYSROOT}${datadir}/pv-llama/models/$m.squashfs
        if [ ! -s "$src" ]; then
            bbfatal "missing model squashfs: $src (is pv-llama-model-$m built?)"
        fi
        cp -f "$src" ${PVSTATE}/${PN}/$m.squashfs
    done
}

PVR_APP_ADD_POST_HOOK = "build_model_squashfs"

PVR_APP_ADD_EXTRA_ARGS += "--config=Entrypoint=/usr/bin/pv-llama-run"
