#!/bin/sh

grep 'validati' /storage/logs/current/pantavisor/pantavisor.log | sed 's/^[^]]*\] *[^ ]* *[^ ]* *-- *\[[^]]*\] *: *//; s/^([a-zA-Z_][a-zA-Z0-9_]*:[0-9]\+) //' | grep -v '^no validation list:' | sed 's/ and id=[0-9a-f]\{64\}/ and id=XXX/; s|/storage/objects/[0-9a-f]\{64\}|/storage/objects/XXX|g' | sort
