header:
    version: 16
_source_dir: .
repos:
    meta-rockchip:
        commit: e641dba980efa885df7e992ac5c8783270aa375d
        path: layers/meta-rockchip-mainline
        url: https://git.yoctoproject.org/meta-rockchip
    meta-arm:
        commit: 60e31ef2c4983c0bdb8682dee6a6ec5f2e9d5f0a
        layers:
            meta-arm:
            meta-arm-toolchain:
        path: layers/meta-arm
        url: git://git.yoctoproject.org/meta-arm
    meta-pantavisor:
    poky:
        url: https://github.com/yoctoproject/poky.git
        path: layers/poky
        layers:
            meta:
            meta-poky:
        patches:
            fit-image-multiconfig:
                path: patches/poky/0001-fit-image-multiconfig.scarthgap.patch
                repo: meta-pantavisor
        commit: 200d12b6a58ad961d60a7774ca0f7a9d29498724
    meta-virtualization:
        commit: 6f3c1d8f90947408a6587be222fec575a1ca5195
        path: layers/meta-virtualization
        url: git://git.yoctoproject.org/meta-virtualization
    meta-openembedded:
        commit: 2e3126c9c16bb3df0560f6b3896d01539a3bfad7
        layers:
            meta-filesystems:
            meta-networking:
            meta-oe:
            meta-python:
        path: layers/meta-openembedded
        url: https://github.com/openembedded/meta-openembedded.git
local_conf_header:
    platform-rockchip: |
        PV_UBOOT_AUTOFDT = "1"
    rm_work: |
        INHERIT += "rm_work"
    panta-base: |
        TMPDIR = "${TOPDIR}/tmp-${DISTRO_CODENAME}"
    panta-busybox: |
        PREFERRED_VERSION_busybox = "1.36~pv.%"
    panta-mbedtls: |
        PREFERRED_VERSION_mbedtls = "2.28.%"
    pantavisor-system: |
        DISTRO_FEATURES:append = " pantavisor-system "
        PANTAVISOR_FEATURES:append = " dm-crypt"
        PANTAVISOR_FEATURES:append = " dm-verity"
        PANTAVISOR_FEATURES:append = " autogrow"
        INITRAMFS_IMAGE = "pantavisor-initramfs"
    pantavisor-remix: |
        IMAGE_CLASSES:append = " image-pvrexport"
    __menu_config_locals: ''
    __menu_config_vars: |-
        PVROOT_IMAGE = "yes"
        PVROOT_IMAGE_BSP = "core-image-base"
        EXTRA_IMAGE_FEATURES:append = " debug-tweaks"
        INHERIT += "rm_work"
    __voldirs: |-
        SSTATE_DIR="/shared/sstate"
        DL_DIR="/shared/dldir"
machine: rock64
target:
- pantavisor-remix
build_system: oe
distro: panta-distro
env:
    PVROOT_IMAGE_BSP:
    PV_BOOT_OEMARGS:
defaults:
    repos:
        branch: scarthgap
