#@TYPE: Machine
#@NAME: native-sim
#@DESCRIPTION: Zephyr native_sim_64 board for local PVCM protocol testing

DEFAULTTUNE = "x86-64"
require conf/machine/include/x86/arch-x86.inc
TUNE_FEATURES:tune-x86-64 = "m64"

TCLIBC = "glibc"
