#!/bin/sh

source /usr/share/pantavisor/pvtest/utils

echo "== phconfig volume config key =="
pvcontrol conf ls | jq '.[] | select(.key == "PV_STORAGE_PHCONFIG_VOL")'

echo "== /storage/config contents =="
_pv_exec ls /storage/config/

echo "== /volumes/bsp/pv--phconfig contents =="
_pv_exec ls /volumes/bsp/pv--phconfig/

echo "== /var/run/pantavisor/pv/phconfig contents =="
_pv_exec ls /run/pantavisor/pv/phconfig/
