#!/bin/sh

source /usr/share/pantavisor/pvtest/utils


pvcontrol conf ls | jq '.[] | select(.key == "PV_STORAGE_PHCONFIG_VOL")'

ls /storage/config/
ls /volumes/bsp/pv--phconfig/
ls /var/run/pantavisor/pv/phconfig/
