#!/bin/sh

source /usr/share/pantavisor/pvtest/utils

# initial setup
pvcontrol devmeta ls | jq -M -r '.["pantavisor.revision"]'
pvr clone http://localhost:12368/cgi-bin/pvr /home/checkout > /dev/null 2>&1
cd /home/checkout

# check secureboot mode
pvcontrol conf ls | jq -M '.[] | select(.key == "PV_SECUREBOOT_MODE")'

# post a new change with a new oem config signed by oem
pvr get /work/local/common/tarballs/pv-oem-developer-001_oemsigned.tgz
pvr checkout
pvr post --rev "locals/error" > /dev/null

# after posting evaluation
pvcontrol devmeta ls | jq -M -r '.["pantavisor.revision"]'
pvcontrol conf ls | jq -M '.[] | select(.key == "PV_SECUREBOOT_MODE")'
pvcontrol steps show-progress locals/error
