name: "MAN: !MACHINE-!YOCTO_BRANCH"

on:
  workflow_dispatch:

jobs:

  build-!MACHINE-!YOCTO_BRANCH:
    uses: ./.github/workflows/buildkas-starter.yaml
    with:
      configs: .github/configs/release/!MACHINE-!YOCTO_BRANCH.yaml:.github/configs/shared-vols.yaml
      machine_name: !MACHINE-!YOCTO_BRANCH
    secrets: inherit