
name: "TAG: !MACHINE-!YOCTO_BRANCH"

on:
  push:
    paths:
      - '**'
      - '.github/configs/**'
      - '!.github/scripts/**'
      - '!.github/templates/**'
    tags:
      - 0*
      - '*-rc*'
jobs:

  build-!MACHINE-!YOCTO_BRANCH:
    uses: ./.github/workflows/buildkas-target.yaml
    with:
      configs: .github/configs/release/!MACHINE-!YOCTO_BRANCH.yaml:.github/configs/shared-vols.yaml
      machine_name: !MACHINE-!YOCTO_BRANCH
      build_target: !BUILD_TARGET
      output: !OUTPUT
    secrets: inherit