require panta-distro.inc

DISTRO = "panta"
DISTRO_NAME = "Pantavisor Remix Distro"
DISTRO_VERSION = "${@oe.buildcfg.get_metadata_git_describe(os.path.dirname(os.path.dirname(d.getVar('FILE'))))}"

# use custom busybox + mbedtls
# kirkstone: recipes-pv/busybox/busybox_1.36~pv.1.bb (forked git source)
# scarthgap: poky's busybox_1.36.1.bb + recipes-pv/busybox/busybox_%.bbappend
BUSYBOX_VERSION_kirkstone = "1.36~pv.%"
BUSYBOX_VERSION_scarthgap = "1.36.%"

PREFERRED_VERSION_busybox = "${@d.getVar("BUSYBOX_VERSION_${DISTRO_CODENAME}", expand=True)}"
PREFERRED_VERSION_mbedtls = "2.28.%"

