
require conf/distro/poky.conf
require panta-appengine.inc

DISTRO = "panta-appengine"
DISTRO_NAME = "Pantavisor Appengine Distro"

DISTRO_VERSION = "${@oe.buildcfg.get_metadata_git_describe(os.path.dirname(os.path.dirname(d.getVar('FILE'))))}"