#!/bin/sh

source /usr/share/pantavisor/pvtest/utils

# initial setup
pvcontrol devmeta ls | jq -M -r '.["pantavisor.revision"]'
pvr clone http://localhost:12368/cgi-bin/pvr /home/checkout > /dev/null 2>&1
cd /home/checkout

# check secureboot mode and signature JSON
pvcontrol conf ls | jq -M '.[] | select(.key == "PV_SECUREBOOT_MODE")'
cd /storage/trails/0/; echo "yes" | pvr sig ls; cd -

# post a new change that breaks strict mode
rm _sigs/pvr-sdk.json
pvr add .
pvr commit > /dev/null 2>&1
pvr post --rev "locals/error" > /dev/null

# after posting evaluation
pvcontrol devmeta ls | jq -M -r '.["pantavisor.revision"]'
pvcontrol conf ls | jq -M '.[] | select(.key == "PV_SECUREBOOT_MODE")'
pvcontrol steps show-progress locals/error
