#!/bin/sh
# Entrypoint for the pv-llama container.
#
# Architecture:
#   xconnect (rest) ──UDS──> socat bridge ──TCP──> llama-swap
#                                                     │ spawns/swaps
#                                                     ▼
#                                                  llama-server (per-model)
#
# llama-swap exposes an OpenAI-compatible HTTP API on TCP. Its config
# (/etc/pv-llama/llama-swap.yaml, generated by the recipe) lists every
# local model and how to launch the matching llama-server backend on
# demand. socat bridges that TCP port onto a UDS so pv-xconnect can
# mediate it as a 'rest' service.
#
# Env (overridable):
#   LLAMA_PORT   TCP port llama-swap listens on (default 8080)
#   LLAMA_UDS    UDS bridged to LLAMA_PORT (default /run/pv-llama/api.sock)
#   LLAMA_SWAP_CONFIG  llama-swap YAML (default /etc/pv-llama/llama-swap.yaml)

set -eu

: "${LLAMA_PORT:=8080}"
: "${LLAMA_UDS:=/run/pv-llama/api.sock}"
: "${LLAMA_SWAP_CONFIG:=/etc/pv-llama/llama-swap.yaml}"

log() {
    printf '%s pv-llama: %s\n' "$(date -Iseconds)" "$*" >&2
}

if [ ! -r "$LLAMA_SWAP_CONFIG" ]; then
    log "FATAL: missing $LLAMA_SWAP_CONFIG"
    exit 1
fi

mkdir -p "$(dirname "$LLAMA_UDS")"
rm -f "$LLAMA_UDS"
log "bridging $LLAMA_UDS -> 127.0.0.1:$LLAMA_PORT (socat)"
socat "UNIX-LISTEN:$LLAMA_UDS,fork,reuseaddr,mode=0660" \
      "TCP:127.0.0.1:$LLAMA_PORT" &
SOCAT_PID=$!
trap 'kill $SOCAT_PID 2>/dev/null || true' EXIT INT TERM

log "starting llama-swap on 127.0.0.1:$LLAMA_PORT (config $LLAMA_SWAP_CONFIG)"
exec llama-swap \
    -config "$LLAMA_SWAP_CONFIG" \
    -listen "127.0.0.1:$LLAMA_PORT"
