# pvgo layer - Isolated Go 1.24 toolchain for Pantavisor
BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"
BBFILE_COLLECTIONS += "pvgo"
BBFILE_PATTERN_pvgo = "^${LAYERDIR}/"
BBFILE_PRIORITY_pvgo = "7"

LAYERSERIES_COMPAT_pvgo = "kirkstone scarthgap styhead"
LAYERDEPENDS_pvgo = "core"
