#!/bin/sh

source /usr/share/pantavisor/pvtest/utils

export CURL_CMD=curl

pvcontrol containers ls | jq -M | tr -d '\r'
pvcontrol groups ls | jq -M | tr -d '\r'
pvcontrol usrmeta ls | jq -M | tr -d '\r'
pvcontrol devmeta ls | jq -M 'del(.storage, .interfaces, .sysinfo, .time, .["pantavisor.uname"], .["pantavisor.cpumodel"], .["pantavisor.version"]) | to_entries | sort_by(.key) | from_entries' | tr -d '\r'
echo "object count: $(pvcontrol objects ls | jq -M 'length' | tr -d '\r')"
pvcontrol steps ls | jq -M 'map(del(.date))' | tr -d '\r'
pvcontrol conf ls | jq -M | tr -d '\r'
