SUMMARY = "Pantavisor Avahi mDNS browse consumer (hosted D-Bus system bus)"
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://${COMMON_LICENSE_DIR}/MIT;md5=0835ade698e0bcf8506ecda2f7b4f302"

inherit image container-pvrexport

IMAGE_BASENAME = "pv-avahi-browse"

PVRIMAGE_AUTO_MDEV = "0"

IMAGE_FSTYPES = "pvrexportit"

# Single-pid consumer: avahi client tools to browse over the injected bus, plus
# dbus-send so the pvtest can drive an explicit D-Bus roundtrip. No dbus-daemon,
# no policy XML: identity is the 'monitor' role, masqueraded by the proxy; the
# bus and its policy are hosted/generated by pantavisor. Same as the other
# Yocto-built containers (cf. pvwificonnect), `inherit image` gives none of
# core-image's defaults, so base-files/base-passwd are listed to provide
# /etc/passwd and the /etc/hostname,/etc/hosts used by set_hostname below.
IMAGE_INSTALL += "busybox avahi-utils dbus base-files base-passwd"

do_fetch[noexec] = "0"
do_unpack[noexec] = "0"

SRC_URI += "file://args.json \
            file://pv-avahi-browse-start.sh \
"

PVR_APP_ADD_GROUP = "app"

install_scripts() {
    install -d ${IMAGE_ROOTFS}${bindir}
    install -m 0755 ${WORKDIR}/pv-avahi-browse-start.sh ${IMAGE_ROOTFS}${bindir}/pv-avahi-browse-start
}

ROOTFS_POSTPROCESS_COMMAND += "install_scripts; set_hostname; "

# base-files' `hostname:pn-base-files` default is `${MACHINE}`, but that
# override is scoped to the base-files recipe, which is shared by every
# image built for the same MACHINE - setting it there would rename every
# container built alongside this one, not just pv-avahi-browse. Overwrite the
# already-installed /etc/hostname (and the matching /etc/hosts entry
# base-files wrote) here instead, so only this image gets a stable,
# machine-independent hostname: its own container name.
set_hostname() {
    echo "${PN}" > ${IMAGE_ROOTFS}${sysconfdir}/hostname
    sed -i "s/^127.0.1.1.*/127.0.1.1 ${PN}/" ${IMAGE_ROOTFS}${sysconfdir}/hosts
}

PVR_APP_ADD_EXTRA_ARGS += "--config=Entrypoint=/usr/bin/pv-avahi-browse-start"
