name: 'Build Kas'

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      configs:
        required: true
        type: string

jobs:
  build-kas:
    runs-on: ["self-hosted"]
    container:
      image: ghcr.io/pantacor/kas/kas:next-v5
      volumes:
        - shared:/shared
      options: --user root
    steps:
      - name: chown
        run: chown -R builder:builder $RUNNER_WORKSPACE
      - name: chowna
        run: chown -R builder:builder /__w
      - name: shared
        run: mkdir -p /shared/sstate && chown builder:builder /shared/sstate && mkdir -p /shared/dldir && chown builder:builder /shared/dldir
      - name: getgit
        run: su - builder -c "cd $GITHUB_WORKSPACE && git fetch origin $GITHUB_SHA && git reset --hard $GITHUB_SHA && rm -rf build/ && git clean -f -f -d -x "
      - name: Build Kas
        run: su - builder -c "cd $GITHUB_WORKSPACE && env && kas build ${{ inputs.configs }}"
      - name: chmod
        run: chmod -R 777 $GITHUB_WORKSPACE
      - name: Archive image artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pantavisor-remix-${{ inputs.name }}
          path: |
            build/tmp-*/deploy/images/*/pantavisor-remix*.wic.*
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pvrexports-${{ inputs.name }}
          path: |
            build/tmp-*/deploy/images/*/*pvrexport.*

