name: "run pvtests"
on:
  workflow_call:
    inputs:
      test_type:
        required: true
        type: string
      test_number:
        required: false
        type: string
jobs:

  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validate test_type input
        run: |
          if [[ "${{ inputs.test_type }}" != "pvtests-local" && "${{ inputs.test_type }}" != "pvtests-remote" ]]; then
            echo "❌ Invalid test_type: '${{ inputs.test_type }}'"
            echo "Allowed values: pvtests-local, pvtests-remote"
            exit 1
          fi
          echo "✅ test_type is valid: ${{ inputs.test_type }}"

          if [[ -n "${{ inputs.test_number }}" ]]; then
            echo "test_number was provided: ${{ inputs.test_number }}"
            echo "=== Running test number: ${{ inputs.test_number }} ==="
            echo "HAS_TEST_NUMBER=true" >> $GITHUB_ENV
          else
            echo "test_number was not provided"
            echo "=== Running All tests ==="
            echo "HAS_TEST_NUMBER=false" >> $GITHUB_ENV
          fi

  build-docker-x86_64-scarthgap:
    uses: ./.github/workflows/buildkas-target.yaml
    with:
      configs: .github/configs/release/docker-x86_64-scarthgap.yaml:.github/configs/shared-vols.yaml
      machine_name: docker-x86_64-scarthgap
      build_target: pantavisor-appengine-distro
      output: pantavisor-appengine-distro-*.tar.gz
      sdk: 0
    secrets: inherit

  pvtests:
    needs: build-docker-x86_64-scarthgap
    runs-on: ["pvtest-runner"]
    steps:
      - name: Download AppEngine artifacts
        uses: actions/download-artifact@v4
        with:
          name: appengine-docker-x86_64-scarthgap
          path: .

      - name: Clone ${{ inputs.test_type }} repository
        run: |
          rm -rf ${{ inputs.test_type }}
          git clone https://gitlab.com/pantacor/${{ inputs.test_type }}.git ${{ inputs.test_type }}

      - name: Load and prepare
        env:
            CI_MODE: "true"
        run: |
          chmod +x test.docker.sh

          for tar in pantavisor-appengine-*-docker.tar pantavisor-appengine-docker.tar; do
            [ -f "$tar" ] && docker load -i "$tar"
          done

          echo "=== Avaliable Tests === "
          ./test.docker.sh ls

      - name: Run pvtests
        run: |
          set -e
          set -o pipefail

          echo "=== AppEngine Test Run started at $(date) ==="

          if [[ "$HAS_TEST_NUMBER" == "true" ]]; then
            echo "--------------------------------------------------------------------------"
            echo "RUNNING ${{ inputs.test_type }}" with test_number:${{ inputs.test_number }}
            echo "--------------------------------------------------------------------------"
            if [[ "${{ inputs.test_type }}" == "pvtests-remote" ]]; then
                PH_USER='${{ secrets.PH_USER }}' PH_PASS='${{ secrets.PH_PASS }}' \
                ./test.docker.sh -v run ${{ inputs.test_type }}:${{ inputs.test_number }}
            else
                ./test.docker.sh -v run ${{ inputs.test_type }}:${{ inputs.test_number }}
            fi

          else
            echo "---------------------------------------------------------------"
            echo "RUNNING ALL TEST: ${{ inputs.test_type }}"
            echo "---------------------------------------------------------------"

            if [[ "${{ inputs.test_type }}" == "pvtests-remote" ]]; then
                PH_USER='${{ secrets.PH_USER }}' PH_PASS='${{ secrets.PH_PASS }}' \
                ./test.docker.sh -v run ${{ inputs.test_type }}
            else
                ./test.docker.sh -v run ${{ inputs.test_type }}
          fi

          LOG_NAME="test.docker-$(date +%s).log"
          cp test.docker.log "$LOG_NAME"
          echo "LOG_NAME=$LOG_NAME" >> $GITHUB_ENV


      - name: Show Tests Summary
        run: |
          sed -n '/=======/,/=======/p' test.docker.log
          sed -n '/=======/,/=======/p' test.docker.log  > summary.log

      - name: Upload test log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pvtests-logs
          path: |
              ${{ env.LOG_NAME }}
              summary.log

      - name: Clean up
        if: always()
        run: |
          docker ps -aq \
          | xargs -r docker inspect --format '{{.Image}} {{.ID}}' \
          | grep -E 'pantavisor-appengine(-netsim|-tester)?' \
          | awk '{print $2}' \
          | xargs -r docker rm -f

          docker images --format '{{.Repository}}:{{.Tag}}' \
          | grep -E '^pantavisor-appengine(-netsim|-tester)?:' \
          | xargs -r docker rmi -f

          rm pantavisor-appengine-*
          rm -rf pvtests-local