name: 'build colibri-imx6ull-scarthgap'

on:
  workflow_call:

jobs:

  build-colibri-imx6ull-scarthgap:
    uses: ./.github/workflows/buildkas.yaml
    with:
      configs: .github/configs/release/colibri-imx6ull-scarthgap.yaml:.github/configs/shared-vols.yaml
      name: colibri-imx6ull-scarthgap
    secrets: inherit
