name: "manual: start pvtests"

on:
  workflow_dispatch:
    inputs:

      test_path:
        description: 'Test path to run (e.g. "local/lifecycle"); leave empty to run all tests'
        required: false
        type: string

jobs:

  build-docker-x86_64-scarthgap:
    uses: ./.github/workflows/buildkas-target.yaml
    with:
      configs: kas/build-configs/release/docker-x86_64-scarthgap.yaml:kas/build-configs/shared-vols.yaml
      machine_name: docker-x86_64-scarthgap
      build_target: pantavisor-appengine-distro
      output: pantavisor-appengine-distro-*.tar.gz
      sdk: 0
    secrets: inherit

  start-pvtest:
    needs: build-docker-x86_64-scarthgap
    uses: ./.github/workflows/call-pvtests.yaml
    with:
      test_path: ${{ inputs.test_path }}
    secrets: inherit
