name: "manual: start pvtests"

on:
  workflow_dispatch:
    inputs:

      test_type:
        description: 'Select the type of the test'
        required: true
        type: choice
        options:
          - pvtests-local
          - pvtests-remote

      test_number:
        description: 'Test number to run (e.g., "0" for remote:0)'
        required: false
        type: string

jobs:

  build-docker-x86_64-scarthgap:
    uses: ./.github/workflows/buildkas-target.yaml
    with:
      configs: .github/configs/release/docker-x86_64-scarthgap.yaml:.github/configs/shared-vols.yaml
      machine_name: docker-x86_64-scarthgap
      build_target: pantavisor-appengine-distro
      output: pantavisor-appengine-distro-*.tar.gz
      sdk: 0
    secrets: inherit

  start-pvtest:
    needs: build-docker-x86_64-scarthgap
    uses: ./.github/workflows/call-pvtests.yaml
    with:
      test_type: ${{ inputs.test_type}}
      test_number: ${{ inputs.test_number }}