name: "manual: start pvtests"

on:
  workflow_dispatch:
    inputs:

      test_type:
        description: 'Select the type of the test'
        required: true
        type: choice
        options:
          - pvtests-local
          - pvtests-remote

      test_number:
        description: 'Test number to run (e.g., "0" for remote:0)'
        required: false
        type: string

jobs:

  start-pvtest:
    uses: ./.github/workflows/call-pvtests.yaml
    with:
      test_type: ${{ inputs.test_type}}
      test_number: ${{ inputs.test_number }}