name: 'onpush built targets - scarthgap-musl'

on:
  push:

jobs:
  build:
    runs-on: ["self-hosted"]
    container:
      image: ghcr.io/pantacor/kas/kas:next-v7
      volumes:
        - shared:/shared
      options: --user root
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: raspberrypi-armv8
            config: .github/configs/release/raspberrypi-armv8-scarthgap.yaml:.github/configs/shared-vols.yaml
          - arch: sunxi-orange-pi-r1
            config: .github/configs/release/sunxi-orange-pi-r1-scarthgap.yaml:.github/configs/shared-vols.yaml

    steps:
      - uses: actions/checkout@v4
      - name: chown
        run: chown -R builder:builder $RUNNER_WORKSPACE
      - name: chowna
        run: chown -R builder:builder /__w
      - name: shared
        run: mkdir -p /shared/sstate && chown builder:builder /shared/sstate && mkdir -p /shared/dldir && chown builder:builder /shared/dldir
      - name: getgit
        run: su - builder -c "cd $GITHUB_WORKSPACE && git fetch origin $GITHUB_SHA && git reset --hard $GITHUB_SHA && rm -rf build/ && git clean -f -f -d -x "
      - name: Build Kas
        run: su - builder -c "cd $GITHUB_WORKSPACE && env && kas build ${{ matrix.config }}"
      - name: chmod
        run: chmod -R 777 $GITHUB_WORKSPACE
      - name: copy files
        run: |
          cp build/tmp-*/deploy/images/*/pantavisor-remix*.rootfs.wic.* .
          cp build/tmp-*/deploy/images/*/*pvrexport.tgz .
          echo $pwd
      - name: Archive image artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pantavisor-remix-${{ matrix.arch }}
          path: |
            pantavisor-remix*.wic.*

      - name: debug
        run: echo $pwd

      - name: Archive pvrexport artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pvrexports-${{ matrix.arch }}
          path: |
            *pvrexport.tgz

