name: 'Build On Push'

on:
  push:
    paths:
      - '**'
      - '.github/configs/**'
      - '!.github/scripts/**'
      - '!.github/workflows/updatemachines.yaml'

jobs:

  build-raspberrypi-armv8-scarthgap:
    uses: ./.github/workflows/buildkas.yaml
    with:
      configs: .github/configs/release/raspberrypi-armv8-scarthgap.yaml
      name: raspberrypi-armv8-scarthgap
    secrets: inherit
