name: 'on push: Raspberry Pi armv8'

on:
  push:
    paths:
      - '**'
      - '.github/configs/**'
      - '!.github/scripts/**'
      - '!.github/workflows/updatemachines.yaml'

jobs:

  build-raspberrypi-armv8-scarthgap:
    uses: ./.github/workflows/buildkas-starter.yaml
    with:
      configs: .github/configs/release/raspberrypi-armv8-scarthgap-bsp.yaml:.github/configs/shared-vols.yaml
      name: raspberrypi-armv8-scarthgap
    secrets: inherit
