name: 'Build Basic'

on:
  push:

jobs:
  build-remix-sunxi:
    runs-on: ["self-hosted"]
    container:
      image: ghcr.io/pantacor/kas/kas:next-v1
      volumes:
        - shared:/shared
    steps:
      - name: chown
        run: sudo chown -R builder:builder .
      - name: shared
        run: sudo mkdir -p /shared/sstate && sudo chown builder:builder /shared/sstate && sudo mkdir -p /shared/dldir && sudo chown builder:builder /shared/dldir
      - name: Build Kas
        run: find .github/configs && kas build .github/configs/sunxi/sunxi-orange-pi-3lts-remix-scarthgap.yaml:.github/configs/shared-vols.yaml
