name: 'Build Basic'

on:
  push:

jobs:
  build-remix-sunxi:
    runs-on: ["self-hosted"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Kas
        uses: ./.github/actions/kas-build
        id: build-kas
        with:
          target: "pantavisor-remix"
          config-dir: ".github/configs/sunxi"
  build-bsp-sunxi:
    runs-on: ["self-hosted"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Kas
        uses: ./.github/actions/kas-build
        id: build-kas
        with:
          target: "pantavisor-bsp"
          config-dir: ".github/configs/sunxi"
  build-remix-nxp:
    runs-on: ["self-hosted"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Kas
        uses: ./.github/actions/kas-build
        id: build-kas
        with:
          target: "pantavisor-remix"
          config-dir: ".github/configs/nxp"
  build-bsp-nxp:
    runs-on: ["self-hosted"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Kas
        uses: ./.github/actions/kas-build
        id: build-kas
        with:
          target: "pantavisor-bsp"
          config-dir: ".github/configs/nxp"

