name: 'Build On Push'

on:
  push:
    paths:
      - '**'
      - '.github/configs/**'
      - '!.github/scripts/**'
      - '!.github/workflows/updatemachines.yaml'

jobs:

  build-imx8qxp-mek-scarthgap:
    uses: ./.github/workflows/buildkas.yaml
    with:
      configs: .github/configs/release/imx8qxp-mek-scarthgap.yaml
      name: imx8qxp-mek-scarthgap
    secrets: inherit
name: 'Build On Push'

on:
  push:
    paths:
      - '**'
      - '.github/configs/**'
      - '!.github/scripts/**'
      - '!.github/workflows/updatemachines.yaml'

jobs:

  build-imx8qxp-mek-scarthgap:
    uses: ./.github/workflows/buildkas.yaml
    with:
      configs: .github/configs/release/imx8qxp-mek-scarthgap.yaml
      name: imx8qxp-mek-scarthgap
    secrets: inherit
