name: "schedule: pvtests"

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  build-docker-x86_64-scarthgap:
    uses: ./.github/workflows/buildkas-target.yaml
    with:
      configs: kas/build-configs/release/docker-x86_64-scarthgap.yaml:kas/build-configs/shared-vols.yaml
      machine_name: docker-x86_64-scarthgap
      build_target: pantavisor-appengine-distro
      output: pantavisor-appengine-distro-*.tar.gz
      sdk: 0
    secrets: inherit

  local:
    needs: build-docker-x86_64-scarthgap
    uses: ./.github/workflows/call-pvtests.yaml
    with:
      test_path: local
    secrets: inherit

  remote:
    needs: [build-docker-x86_64-scarthgap, local]
    if: always()
    uses: ./.github/workflows/call-pvtests.yaml
    with:
      test_path: remote
    secrets: inherit
