name: 'Schedule - sunxi-orange-pi-3lts-scarthgap'

on:
  workflow_dispatch:
  schedule:
   - cron: "15 */8 * * *"

jobs:

  build-sunxi-orange-pi-3lts-scarthgap:
    uses: ./.github/workflows/buildkas-starter.yaml
    with:
      configs: .github/configs/release/sunxi-orange-pi-3lts-scarthgap.yaml:.github/configs/shared-vols.yaml
      machine_name: sunxi-orange-pi-3lts-scarthgap
    secrets: inherit
