name: "ontag: sync and release"

on:
  push:
    paths:
      - '**'
      - 'kas/build-configs/**'
      - '.github/workflows/tag-scarthgap.yaml'
      - '!.github/scripts/**'
      - '!.github/templates/**'
    tags:
      - 0*
      - '*-rc*'

jobs:
  sync:
    uses: ./.github/workflows/sync-pantavisor.yaml
    secrets: inherit

  release:
    needs: sync
    uses: ./.github/workflows/release.yaml
    secrets: inherit
