#!/bin/sh

source /usr/share/pantavisor/pvtest/utils
PVR_USERNAME="$PH_USER" PVR_PASSWORD="$PH_PASS" pvr login > /dev/null 2>&1

wait_for_pantahub_state "pvr-sdk" "claim" \
    || { echo "ERROR: timeout waiting for pantahub.state claim" >&2; exit 1; }
pvcontrol devmeta ls | jq -M -r '.["pantahub.state"]'

device_id=`cat /var/run/pantavisor/pv/device-id`
challenge=`cat /var/run/pantavisor/pv/challenge`

pvr claim -c "$challenge" "$device_id"

wait_for_pantahub_state "pvr-sdk" "idle" \
    || { echo "ERROR: timeout waiting for pantahub.state idle" >&2; exit 1; }
pvcontrol devmeta ls | jq -M -r '.["pantahub.state"]'

if [ -n "$device_id" ]; then
	pvr dev delete -y $device_id
fi
